# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a72cbea6237b31ac456085c8a769a8ddd07245da242b766d506d45f9dc8751f2ae18bf89ab269f36684b20a77f1c1623d46fd274e4902127cca65e00870e16f

test:
  secret_key_base: 5041d6361e657e766522467d5a84306afd270f2554658c5925c97fe5740f4955adaa735c0a8949b6dc1248ad0f4b0ee186d1958b6288b237b78a8be416c8abb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
